### ISSUE TITLE
Expand schema with a `canonicalize` method

### ISSUE THREAD

**Issue by matwilko** [humanwhocodes/config-array#98]
While delving into all the code behind the new config system in ESLint, I've noted a repeating pattern of helper functions that convert various parts of configuration into a "canonical" form - e.g. rule configuration canonicalizing severities to their number form, raw severity -> array, plugin function-style to object-style, and so on.

More generally, for many parts of the configuration, there are multiple ways to express the same thing, but there's often a single canonical way to express it that the rest of the system would have an easier time processing.

I think `config-array` could help out here by allowing these operations to be centralized in the schema itself, and by applying the canonicalization at the right moment, it could mean that every other part of the system (including say, `merge`) would only need to need to handle the canonicalized form of the configuration, rather than applying it locally.

As an example, the ESLint `rulesSchema` could be expanded like so:

```js
const ruleSeverities = { 0: 0, "off": 0, 1: 1, "warn": 1, 2: 2, "error": 2 };
const rulesSchema = {

    canonicalize(rules) {
        const canonicalisedRules = Object.create(null);
        for (const ruleName in Object.keys(rules) {

            if (ruleName === "__proto__") { continue; }

            let rule = rules[ruleName];

            if (typeof rule === 'string' || typeof rule === 'number') {
                rule = [rule];
            }

            rule[0] = ruleSeverities[rule[0]];
            
            if (rule[0] === 0) {
                rule = [0];
            }

            canonicalisedRules[ruleName] = rule;
        }

        return canonicalisedRules;
    }

    merge(first = {}, second = {}) {
        // Now merge only has to deal with the canonicalised forms of the rules and doesn't need to do any conversions itself
        const result = {
            ...first,
            ...second
        };

        for (const ruleId of Object.keys(result)) {

            /*
             * If either rule config is missing, then the correct
             * config is already present.
             */
            if (!(ruleId in first) || !(ruleId in second)) {
                continue;
            }

            const firstRuleOptions = first[ruleId];
            const secondRuleOptions = second[ruleId];

            // If the second rule config disabled the rule, then we're done.
            if (secondRuleOptions[0] === 0) {
                continue;
            }

            /*
             * If the second rule config only has a severity (length of 1),
             * then use that severity and keep the rest of the options from
             * the first rule config.
             */
            if (secondRuleOptions.length === 1) {
                result[ruleId] = [secondRuleOptions[0], ...firstRuleOptions.slice(1)];
                continue;
            }

            /*
             * In any other situation, then the second rule config takes
             * precedence. That means the value at `result[ruleId]` is
             * already correct and no further work is necessary.
             */
        }

        return result;
    },

    validate(value) {
        ...
    }
};

```

I know that `preprocessConfig` is in place already to possibly enable this sort of processing, but it seems like a common enough use-case that an explicit mechanism in the schema would improve the locality of these conversions, and simplify other parts of the system that no longer have to deal with different potential formats.

I'm happy to put together a PR of what this could look like, and work out the detailed semantics of exactly when/where the canonicalization would happen (preferably as lazily and late as possible).

**Comment by nzakas** [comment]
The canonicalization is really an ESLint-specific phenomena that isn't related to this utility generically. Any proposed changes should happen in the ESLint repo.
